### PR TITLE
Add gnome-builder and uktools

### PR DESCRIPTION
**Pull request by usbkey9**

### CODE REVIEW

**Comment by luongvo209** [comment]
Hi @usbkey9 , can you change the link to uktools? It is now pointing to a profile not a repository.

**Comment by usbkey9** [comment]
Done

**Comment by luongvo209** [comment]
Hi @usbkey9 , thank you for your suggestion. However, I still have some concerns:
1. Can we put Gnome builder under [Multi language Support](https://github.com/luongvo209/Awesome-Linux-Software#multiple-languages-support) because I think it is better that way. 
2. The uktools' link is not fixed in other languages. 
3. Why is there so many forks of uktools? Is the original version not maintained anymore? Are you the current maintainer? The idea is cool but do you have any screenshots/videos (from you or any others) that ensures the tool works(I read your code and understood what you are trying to do but I am sorry I couldn't try this on my machine ) ?

**Comment by usbkey9** [comment]
Hi Luong,

1) It isn't better to merge multi language support and editor lists, they
are very close
2) I ever fixed it (except in Thai). Do you want ?
3) Because old maintainers don't even maintain anymore. Yes

**Comment by luongvo209** [comment]
Thank you for your confirmation 😄  @usbkey9

**Pull request merged**
