### PR TITLE
add Marble

### PR DESCRIPTION
**Pull request by chrunchyjesus**

### CODE REVIEW

**Comment by luongvo209** [comment]
Hey @chrunchyjesus . I haven't reviewed this yet. This is pretty off topic, but how do you feel about moving this to Gitlab? Since you are one of the most active person in this repo I would like to hear your opinions

**Comment by chrunchyjesus** [comment]
I am currently moving all of my projects to Gitlab. Seems like there are a lot of other people doing this too and Gitlab is a bit under heavy load. It might be preferable to wait for a while for the migration to cool down, because as it stands now, I do not even know whether the official Gitlab.com servers can survive this movement.

I do not know how it would impact this project's contribution (and your income) since Github is still the bigger one of the two. If you decide to move to Gitlab, having a public read only mirror on Github would certainly help the accessibility of this repository.

**Comment by dyoungwd** [comment]
Bitbucket is another possibility

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com <https://tutanota.com>

4. Jun 2018 17:48 by notifications@github.com <mailto:notifications@github.com>:

**Comment by chrunchyjesus** [comment]
Isn't Bitbucket proprietary?

**Comment by dyoungwd** [comment]
Don't think so, fairly sure it's opensource

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com <https://tutanota.com>

4. Jun 2018 19:21 by notifications@github.com <mailto:notifications@github.com>:

**Comment by luongvo209** [comment]
Moving discussion to #375 to keep this clean

**Comment by luongvo209** [comment]
Another good find. Thank you @chrunchyjesus

**Pull request merged**
