### PR TITLE
add musescore

### PR DESCRIPTION
**Pull request by chrunchyjesus**

### CODE REVIEW

**Comment by luongvo209** [comment]
Hi @chrunchyjesus , the open source link for muse seems to be wrong. Can you fix that ? I have tried the app and thought it was very good. I will merge this right after your fix. 🛩

**Comment by chrunchyjesus** [comment]
Oh sorry. I forgot to change the link after copying the line from another entry. It is fixed now.

**Comment by luongvo209** [comment]
Thank you so much @chrunchyjesus

**Comment by chrunchyjesus** [comment]
No problem.

**Pull request merged**
